version: "3.8"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PORT=80
    env_file:
      - .env
    restart: unless-stopped
