import type { Metadata } from "next";
import { Lato } from "next/font/google";

const lato = Lato({
  variable: "--font-lato", // Ensure this matches usage
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"], // Ensure this is a string array
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.variable}>
      {children}
        </body>
    </html>
  );
}
