import { Lato } from "next/font/google";
import "./globals.css"; // Ensure global styles are imported
import Header from "./Components/common/Header";
import Footer from "./Components/common/Footer";
import HeaderNav from "./Components/common/HeaderNav";

const lato = Lato({
  variable: "--font-lato", // Ensure this matches usage
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"], // Ensure this is a string array
});

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.variable}>
          <HeaderNav/>
        <div className="menu_slider_ara">
          <Header/>
        </div>
        <div className="body_content_area"> 
          {children}
        </div>
        <Footer/>
        </body>
    </html>
  );
}
