import { Lato } from "next/font/google";
// import "../assets/globals.css"; // Ensure global styles are imported
import { Header, Footer, HeaderNav } from "../Components";

const lato = Lato({
  variable: "--font-lato", // Ensure this matches usage
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"], // Ensure this is a string array
});

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.variable}>
      {children}
        </body>
    </html>
  );
}
