import type { Metadata } from "next";
import { Noto_Serif_Display, Noto_Sans, Fustat } from "next/font/google";
import "./globals.css";

const notoSerifDisplay = Noto_Serif_Display({
  subsets: ["latin"],
  variable: "--noto-serif-display",
  style: ["normal", "italic"],
  weight: ["400", "600", "700"],
});

const notoSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--noto-sans",
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],  
});

const fustat = Fustat({
  subsets: ["latin"],
  variable: "--fustat",
  weight: ["400", "500", "600", "700", "800"],
  style: ["normal"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSerifDisplay.variable} ${notoSans.variable} ${fustat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
