/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as PostIndexRouteImport } from './routes/post.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SkillsNewRouteImport } from './routes/skills/new'
import { Route as SkillsSkillidRouteImport } from './routes/skills/$skillid'
import { Route as PostPostidRouteImport } from './routes/post.$postid'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as PostPostdetailsPostidRouteImport } from './routes/post.postdetails.$postid'
import { Route as PostPostidEditRouteImport } from './routes/post.$postid.edit'
import { Route as UsersUsernameSkillsSkillidRouteImport } from './routes/users/$username/skills/$skillid'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIndexRoute = PostIndexRouteImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const SkillsNewRoute = SkillsNewRouteImport.update({
  id: '/skills/new',
  path: '/skills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSkillidRoute = SkillsSkillidRouteImport.update({
  id: '/skills/$skillid',
  path: '/skills/$skillid',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostidRoute = PostPostidRouteImport.update({
  id: '/post/$postid',
  path: '/post/$postid',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const PostPostdetailsPostidRoute = PostPostdetailsPostidRouteImport.update({
  id: '/post/postdetails/$postid',
  path: '/post/postdetails/$postid',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostidEditRoute = PostPostidEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PostPostidRoute,
} as any)
const UsersUsernameSkillsSkillidRoute =
  UsersUsernameSkillsSkillidRouteImport.update({
    id: '/users/$username/skills/$skillid',
    path: '/users/$username/skills/$skillid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/post/$postid': typeof PostPostidRouteWithChildren
  '/skills/$skillid': typeof SkillsSkillidRoute
  '/skills/new': typeof SkillsNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/post/': typeof PostIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/post/$postid/edit': typeof PostPostidEditRoute
  '/post/postdetails/$postid': typeof PostPostdetailsPostidRoute
  '/users/$username/skills/$skillid': typeof UsersUsernameSkillsSkillidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/post/$postid': typeof PostPostidRouteWithChildren
  '/skills/$skillid': typeof SkillsSkillidRoute
  '/skills/new': typeof SkillsNewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/post': typeof PostIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/post/$postid/edit': typeof PostPostidEditRoute
  '/post/postdetails/$postid': typeof PostPostdetailsPostidRoute
  '/users/$username/skills/$skillid': typeof UsersUsernameSkillsSkillidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/post/$postid': typeof PostPostidRouteWithChildren
  '/skills/$skillid': typeof SkillsSkillidRoute
  '/skills/new': typeof SkillsNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/post/': typeof PostIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/post/$postid/edit': typeof PostPostidEditRoute
  '/post/postdetails/$postid': typeof PostPostdetailsPostidRoute
  '/users/$username/skills/$skillid': typeof UsersUsernameSkillsSkillidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/contact'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/post/$postid'
    | '/skills/$skillid'
    | '/skills/new'
    | '/dashboard/'
    | '/post/'
    | '/skills/'
    | '/post/$postid/edit'
    | '/post/postdetails/$postid'
    | '/users/$username/skills/$skillid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/post/$postid'
    | '/skills/$skillid'
    | '/skills/new'
    | '/dashboard'
    | '/post'
    | '/skills'
    | '/post/$postid/edit'
    | '/post/postdetails/$postid'
    | '/users/$username/skills/$skillid'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/contact'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/post/$postid'
    | '/skills/$skillid'
    | '/skills/new'
    | '/dashboard/'
    | '/post/'
    | '/skills/'
    | '/post/$postid/edit'
    | '/post/postdetails/$postid'
    | '/users/$username/skills/$skillid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PostPostidRoute: typeof PostPostidRouteWithChildren
  SkillsSkillidRoute: typeof SkillsSkillidRoute
  SkillsNewRoute: typeof SkillsNewRoute
  PostIndexRoute: typeof PostIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  PostPostdetailsPostidRoute: typeof PostPostdetailsPostidRoute
  UsersUsernameSkillsSkillidRoute: typeof UsersUsernameSkillsSkillidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/': {
      id: '/post/'
      path: '/post'
      fullPath: '/post/'
      preLoaderRoute: typeof PostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/skills/new': {
      id: '/skills/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof SkillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$skillid': {
      id: '/skills/$skillid'
      path: '/skills/$skillid'
      fullPath: '/skills/$skillid'
      preLoaderRoute: typeof SkillsSkillidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postid': {
      id: '/post/$postid'
      path: '/post/$postid'
      fullPath: '/post/$postid'
      preLoaderRoute: typeof PostPostidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/post/postdetails/$postid': {
      id: '/post/postdetails/$postid'
      path: '/post/postdetails/$postid'
      fullPath: '/post/postdetails/$postid'
      preLoaderRoute: typeof PostPostdetailsPostidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postid/edit': {
      id: '/post/$postid/edit'
      path: '/edit'
      fullPath: '/post/$postid/edit'
      preLoaderRoute: typeof PostPostidEditRouteImport
      parentRoute: typeof PostPostidRoute
    }
    '/users/$username/skills/$skillid': {
      id: '/users/$username/skills/$skillid'
      path: '/users/$username/skills/$skillid'
      fullPath: '/users/$username/skills/$skillid'
      preLoaderRoute: typeof UsersUsernameSkillsSkillidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface PostPostidRouteChildren {
  PostPostidEditRoute: typeof PostPostidEditRoute
}

const PostPostidRouteChildren: PostPostidRouteChildren = {
  PostPostidEditRoute: PostPostidEditRoute,
}

const PostPostidRouteWithChildren = PostPostidRoute._addFileChildren(
  PostPostidRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PostPostidRoute: PostPostidRouteWithChildren,
  SkillsSkillidRoute: SkillsSkillidRoute,
  SkillsNewRoute: SkillsNewRoute,
  PostIndexRoute: PostIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  PostPostdetailsPostidRoute: PostPostdetailsPostidRoute,
  UsersUsernameSkillsSkillidRoute: UsersUsernameSkillsSkillidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
