/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as SkillsNewRouteImport } from './routes/skills/new'
import { Route as SkillsSkillidRouteImport } from './routes/skills/$skillid'
import { Route as UsersUsernameSkillsSkillidRouteImport } from './routes/users/$username/skills/$skillid'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsNewRoute = SkillsNewRouteImport.update({
  id: '/skills/new',
  path: '/skills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSkillidRoute = SkillsSkillidRouteImport.update({
  id: '/skills/$skillid',
  path: '/skills/$skillid',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernameSkillsSkillidRoute =
  UsersUsernameSkillsSkillidRouteImport.update({
    id: '/users/$username/skills/$skillid',
    path: '/users/$username/skills/$skillid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/skills/$skillid': typeof SkillsSkillidRoute
  '/skills/new': typeof SkillsNewRoute
  '/skills/': typeof SkillsIndexRoute
  '/users/$username/skills/$skillid': typeof UsersUsernameSkillsSkillidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/skills/$skillid': typeof SkillsSkillidRoute
  '/skills/new': typeof SkillsNewRoute
  '/skills': typeof SkillsIndexRoute
  '/users/$username/skills/$skillid': typeof UsersUsernameSkillsSkillidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/skills/$skillid': typeof SkillsSkillidRoute
  '/skills/new': typeof SkillsNewRoute
  '/skills/': typeof SkillsIndexRoute
  '/users/$username/skills/$skillid': typeof UsersUsernameSkillsSkillidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/skills/$skillid'
    | '/skills/new'
    | '/skills/'
    | '/users/$username/skills/$skillid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/skills/$skillid'
    | '/skills/new'
    | '/skills'
    | '/users/$username/skills/$skillid'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/skills/$skillid'
    | '/skills/new'
    | '/skills/'
    | '/users/$username/skills/$skillid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  SkillsSkillidRoute: typeof SkillsSkillidRoute
  SkillsNewRoute: typeof SkillsNewRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  UsersUsernameSkillsSkillidRoute: typeof UsersUsernameSkillsSkillidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/new': {
      id: '/skills/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof SkillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$skillid': {
      id: '/skills/$skillid'
      path: '/skills/$skillid'
      fullPath: '/skills/$skillid'
      preLoaderRoute: typeof SkillsSkillidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$username/skills/$skillid': {
      id: '/users/$username/skills/$skillid'
      path: '/users/$username/skills/$skillid'
      fullPath: '/users/$username/skills/$skillid'
      preLoaderRoute: typeof UsersUsernameSkillsSkillidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  SkillsSkillidRoute: SkillsSkillidRoute,
  SkillsNewRoute: SkillsNewRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  UsersUsernameSkillsSkillidRoute: UsersUsernameSkillsSkillidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
