import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  //variable: "--body-font",
  subsets: ["latin"],
  weight: ["400","500","600","700"],
  display: "swap",
});

export const metadata = {
  title: "Meta Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
